import * as address from "./address";
import * as appletCar from "./appletCar";
import * as car from "./car";
import * as carrier from "./carrier";
import * as consigneInfo from "./consigneInfo";
import * as device from "./device";
import * as dictionary from "./dictionary";
import * as file from "./file";
import * as goodsInfo from "./goodsInfo";
import * as homepage from "./homepage";
import * as orderCost from "./orderCost";
import * as orderDevices from "./orderDevices";
import * as orderDevicesLocation from "./orderDevicesLocation";
import * as requestOrder from "./requestOrder";
import * as shippingPerson from "./shippingPerson";
import * as userInfo from "./userInfo";
import * as wxCarrierApp from "./wxCarrierApp";
import * as wxEyeTrack from "./wxEyeTrack";

export const api1 = {};

api1.address = address;
api1.appletCar = appletCar;
api1.car = car;
api1.carrier = carrier;
api1.consigneInfo = consigneInfo;
api1.device = device;
api1.dictionary = dictionary;
api1.file = file;
api1.goodsInfo = goodsInfo;
api1.homepage = homepage;
api1.orderCost = orderCost;
api1.orderDevices = orderDevices;
api1.orderDevicesLocation = orderDevicesLocation;
api1.requestOrder = requestOrder;
api1.shippingPerson = shippingPerson;
api1.userInfo = userInfo;
api1.wxCarrierApp = wxCarrierApp;
api1.wxEyeTrack = wxEyeTrack;
